@baseUrl = http://localhost:9090

### 1) Health check
GET {{baseUrl}}/
Accept: application/json

### 2) Register user
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Khushi",
  "email": "khushi@example.com",
  "password": "pass1234",
  "username": "khushi01"
}

### 3) Login user
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "mayank@example.com",
  "password": "pass1234"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "khushi@example.com",
  "password": "pass1234"
}

### 4) Update Profile Picture
POST {{baseUrl}}/uploadProfilePicture
Content-Type: application/json

{
  "profile_picture" : "file path",
  "token": "get the token after user login"
}

### 5) Get User and their profile
GET {{baseUrl}}/get_user_and_profile
Content-Type: application/json

{
  "token": "20b4f1bf479c23834b2b54d2a4e895b57a8dcf9226b02f43a1356ca5ed1ae93f"
}

### 6) Update profile data
POST {{baseUrl}}/update_profile_data
Content-Type: application/json

{
  "token": "20b4f1bf479c23834b2b54d2a4e895b57a8dcf9226b02f43a1356ca5ed1ae93f",
  "bio":"",
  "currentPost": "CTO",
  "pastWork": [
    {
      "company": "Microsoft",
      "position": "CTO",
      "years": "2+"
    }
  ],
  "education": [
    {
      "school": "IIMT",
      "degree": "BCA",
      "fieldOfStudy": "2023-2026"
    }
  ]
}

### 7) Get All user profiles
GET {{baseUrl}}/user/get_all_users
Content-Type: application/json
